### PR TITLE
Create API

### PR DESCRIPTION
**Pull request by SoniEx2**
This is untested. I don't know how to test this.

### CODE REVIEW

**Comment by thraaawn** [comment]
Interesting. Thanks for that.

@NPException42, @Jezza. What do you guys think? If any of us plans to add an API we might want to think about sharing one, so implementing mods support both Dimensional Pockets as well as Compact Machines.

**Comment by NPException42** [comment]
I'll cite Jezza's oppinion on that idea here: "That's fucking awesome!"

I really like that idea too. We should stick our heads together and engineer something amazing. :D

**Comment by NPException42** [comment]
Btw: Can someone summarize for me what this pull request is supposed to be doing?

**Comment by thraaawn** [comment]
It allows other mods to ask IBlockProxy blocks what other blocks they are connecting to.
I.e. if Steve's factory manager cable stumbles upon a Dimensional Pocket implementing IBlockProxy it could ask for all blocks it is connected to and receives one (or more if entangled) BlockLocation where it should continue searching for more cables/interfaces/whatever.

**Comment by NPException42** [comment]
Thanks for the summary. That sounds pretty neat actually. We should talk about that sometime next week

**Comment by SoniEx2** [comment]
Just in case: Feel free to use it (the IBlockProxy and the inner class) under the MIT license.

**Comment by Jezza** [comment]
I definitely love this idea.
I think if we're going to do it properly we need to sit down and think about it.

**Comment by SoniEx2** [comment]
Ok. But please keep it simple stupid.

**Comment by NPException42** [comment]
thats the plan :)

**Pull request closed without merging**
